version: '3.8'

services:
  storageservice:
    build:
      context: .
      dockerfile: StorageService/Dockerfile
    ports:
      - "5001:5001"  # HTTP/1.1 for REST API and file uploads
      - "5002:5002"  # HTTP/2 for gRPC
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001;http://+:5002
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY:-storage-service-secret-2024}
    networks:
      - app-network

  presignedapp:
    build:
      context: .
      dockerfile: PreSignedUrlApp/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - StorageService__SecretKey=${STORAGE_SECRET_KEY:-storage-service-secret-2024}
      - ASPNETCORE_URLS=http://+:5003
    depends_on:
      - storageservice
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
